#!/usr/bin/env bash
# Re-emit `src-tauri/src/aerorsync/` as a standalone crate.
#
# The module is on its way out of this repository (phase E of the standalone
# crate plan). Until it leaves, the invariant that it does not depend on the
# application is checked by two guards that read the source as text, and a text
# scan can only refuse the spellings someone thought of: a review got one of
# them to pass while the module really did import `crate::settings`, with
# `use crate as app;`. This script exists so the invariant is proved by the
# compiler instead. Emitted here, the module is its own crate: any path that
# reaches the application does not resolve.
#
# The emitted crate keeps the module's own directory, `src/aerorsync/`, with a
# `lib.rs` that declares it. That is not cosmetic. The module addresses its own
# fixtures through `CARGO_MANIFEST_DIR/src/aerorsync/...` and two of its tests
# read that directory to scan the source; flattening the tree and rewriting
# `crate::aerorsync::` broke both, and the rewrite itself was the weak point a
# reviewer went for, because a `sed` that hides a dependency blinds the
# compiler that is supposed to find it. Nothing is rewritten now: the paths the
# code declares are the paths it gets.
#
# Idempotent: two runs from the same source produce the same tree and the same
# manifest, which is what phase E0 needs from it.
#
# Usage: scripts/aerorsync-emit.sh [outdir]     (default: target/aerorsync-standalone)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/src-tauri/src/aerorsync"
OUT="${1:-$ROOT/target/aerorsync-standalone}"

[ -d "$SRC" ] || { echo "sorgente assente: $SRC" >&2; exit 1; }

# The script removes the output directory before writing it, so a mistyped
# argument would delete whatever was named. Refuse anything that is not clearly
# a scratch destination: the repository itself, its source trees, and any
# ancestor of them.
OUT="$(mkdir -p "$OUT" 2>/dev/null && cd "$OUT" && pwd -P)" || {
    echo "outdir non utilizzabile: ${1:-}" >&2; exit 1; }
case "$OUT" in
    "$ROOT"|"$ROOT/"|/|"$HOME")
        echo "rifiuto: l'outdir e' il repository o la home ($OUT)" >&2; exit 1;;
esac
for guarded in "$ROOT/src-tauri" "$ROOT/scripts" "$ROOT/.github" "$ROOT/src" "$ROOT/docs"; do
    case "$OUT" in
        "$guarded"|"$guarded"/*)
            echo "rifiuto: l'outdir sta dentro un albero sorgente ($OUT)" >&2; exit 1;;
    esac
done
case "$ROOT" in
    "$OUT"/*) echo "rifiuto: l'outdir contiene il repository ($OUT)" >&2; exit 1;;
esac

rm -rf "$OUT"
mkdir -p "$OUT/src/aerorsync"

# 1. The module keeps its place inside the crate. Only the feature gate goes:
#    here the crate IS the feature.
for f in "$SRC"/*.rs; do
    sed -e '/^#!\[cfg(feature = "aerorsync")\]$/d' \
        -e 's/#\[cfg(feature = "aerorsync")\]//g' \
        -e 's/cfg(all(test, feature = "aerorsync"))/cfg(test)/g' \
        "$f" > "$OUT/src/aerorsync/$(basename "$f")"
done

cat > "$OUT/src/lib.rs" <<'LIB'
// Generated by scripts/aerorsync-emit.sh. Do not edit by hand: edit the script.
//
// The crate is the module and nothing else. If any file under `src/aerorsync/`
// names an application module, the path does not resolve here and the build
// fails, which is the whole point of emitting this.
pub mod aerorsync;
LIB

# 2. The fixtures, at the path the code asks for rather than a path chosen
#    here. The constant is read from the source, so the two cannot drift: if
#    the module moves its transcript, this follows without being edited.
FROZEN_REL="$(sed -n 's/^pub const REAL_RSYNC_FROZEN_TRANSCRIPT_REL: &str = "\(.*\)";$/\1/p' \
    "$SRC/fixtures.rs")"
[ -n "$FROZEN_REL" ] || { echo "non trovo REAL_RSYNC_FROZEN_TRANSCRIPT_REL in fixtures.rs" >&2; exit 1; }
FROZEN_SRC="$ROOT/src-tauri/$FROZEN_REL"
if [ -d "$FROZEN_SRC" ]; then
    mkdir -p "$OUT/$FROZEN_REL"
    cp -a "$FROZEN_SRC/." "$OUT/$FROZEN_REL/"
    emitted="$(find "$OUT/$FROZEN_REL" -type f | wc -l)"
    origin="$(find "$FROZEN_SRC" -type f | wc -l)"
    if [ "$emitted" != "$origin" ] || [ "$emitted" -eq 0 ]; then
        echo "fixture incomplete: $emitted file emessi contro $origin" >&2
        exit 1
    fi
    echo "fixture congelate: $emitted file in $FROZEN_REL"
else
    # Not a warning on stderr that a caller can ignore: without the transcript
    # the oracle tests return early AND PASS, so an emission without fixtures
    # produces a green that means nothing.
    echo "fixture congelate assenti in $FROZEN_SRC: la suite emessa sarebbe verde senza provare nulla" >&2
    exit 1
fi

# 3. The manifest. Versions are read from the application's own Cargo.toml, not
#    from a list kept by hand here: a list would drift the day someone bumps a
#    dependency, and the drift would show up as a compile error nobody expects.
APP_MANIFEST="$ROOT/src-tauri/Cargo.toml"
dep() {
    local name="$1" line
    line="$(grep -m1 "^$name = " "$APP_MANIFEST" || true)"
    [ -n "$line" ] || { echo "dipendenza non trovata nel manifest dell'app: $name" >&2; exit 1; }
    line="${line%%#*}"
    echo "${line//, optional = true/}" | sed 's/optional = true, //; s/[[:space:]]*$//'
}

{
    cat <<'HEAD'
# Generated by scripts/aerorsync-emit.sh. Do not edit by hand: edit the script.
[package]
name = "aerorsync"
version = "0.1.0-alpha.1"
edition = "2021"
publish = false

[lints.rust]
# The lane 3 tests are gated on a cfg the harness sets with RUSTFLAGS. Declared
# for the same reason the application declares it: without this, `-D warnings`
# turns every one of those gates into an error.
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(ci_lane3)'] }

[dependencies]
HEAD
    for d in async-trait russh secrecy serde sha2 ssh2 tokio xxhash-rust \
             libc zstd tracing md-5 md4 sha1 base64 hex filetime; do
        dep "$d"
    done
    # flate2 needs a zlib backend for `Compress::new_with_window_bits`, which
    # `real_wire.rs` calls to speak the rsync deflate stream. In the
    # application that backend is on by accident: `zip`, pulled for archive
    # support, enables `zlib-rs`, and cargo unifies the features. Nothing
    # declares the dependency, so the day `zip` changes the module stops
    # compiling for a reason nobody would connect to it. Declared here.
    echo 'flate2 = { version = "1.0", features = ["zlib-rs"] }'
    cat <<'ACL'

[target.'cfg(target_os = "linux")'.dependencies]
ACL
    for d in acl-sys posix-acl; do
        dep "$d"
    done
    cat <<'DEV'

[dev-dependencies]
DEV
    # Test-only, and only visible once the tests are compiled here.
    for d in tempfile serde_json rand_010; do
        dep "$d"
    done
} > "$OUT/Cargo.toml"

# 4. A manifest of what was emitted. Every entry that is not a directory, with
#    its mode, so a symlink or a permission change is part of what two runs
#    compare. It certifies the emitted TREE, not the dependency resolution:
#    no lockfile is emitted, so `cargo check` resolves compatible versions from
#    the registry and can pick different ones over time with this manifest
#    unchanged.
( cd "$OUT" && find . ! -type d ! -name 'EMITTED.sha256' -printf '%m %p\n' \
    | LC_ALL=C sort ) > "$OUT/EMITTED.modes"
( cd "$OUT" && find . -type f ! -name 'EMITTED.sha256' ! -name 'EMITTED.modes' \
    | LC_ALL=C sort | xargs sha256sum; cat EMITTED.modes ) > "$OUT/EMITTED.sha256"

echo "emesso in $OUT"
echo "voci: $(grep -c . "$OUT/EMITTED.sha256")"
echo "manifest: $(sha256sum "$OUT/EMITTED.sha256" | cut -d' ' -f1)"
