#!/usr/bin/env bash
# Re-emit `src-tauri/src/aerorsync/` as a standalone crate.
#
# The module is on its way out of this repository (phase E of the standalone
# crate plan). Until it leaves, the invariant that it does not depend on the
# application is checked by two guards that read the source as text, and a text
# scan can only refuse the spellings someone thought of: a second reviewer got
# one of them to pass while the module really did import `crate::settings`,
# with `use crate as app;`. This script exists so the invariant is proved by
# the compiler instead. Emitted here, the module is its own crate: any path
# that reaches the application does not resolve, whatever it is spelled like,
# and so does any coupling no import scan can see, a `CARGO_MANIFEST_DIR` that
# points somewhere else, a feature that is not declared, a build script.
#
# Idempotent: two runs from the same source produce the same tree and the same
# manifest, which is what phase E0 needs from it.
#
# Usage: scripts/aerorsync-emit.sh [outdir]        (default: target/aerorsync-standalone)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/src-tauri/src/aerorsync"
OUT="${1:-$ROOT/target/aerorsync-standalone}"

[ -d "$SRC" ] || { echo "sorgente assente: $SRC" >&2; exit 1; }

rm -rf "$OUT"
mkdir -p "$OUT/src"

# 1. The module's flat directory becomes the crate's `src/`. `mod.rs` is the
#    crate root, so it becomes `lib.rs`.
for f in "$SRC"/*.rs; do
    name="$(basename "$f")"
    dest="$OUT/src/$name"
    [ "$name" = "mod.rs" ] && dest="$OUT/src/lib.rs"
    # `crate::aerorsync::x` addresses a submodule of this crate now, so the
    # prefix goes; the feature gate does not exist here, the crate IS the
    # feature.
    sed -e 's/crate::aerorsync::/crate::/g' \
        -e '/^#!\[cfg(feature = "aerorsync")\]$/d' \
        -e 's/#\[cfg(feature = "aerorsync")\]//g' \
        -e 's/cfg(all(test, feature = "aerorsync"))/cfg(test)/g' \
        "$f" > "$dest"
done

# 2. The manifest. Versions are read from the application's own Cargo.toml, not
#    from a list kept by hand here: a list would drift the day someone bumps a
#    dependency, and the drift would show up as a compile error nobody expects.
APP_MANIFEST="$ROOT/src-tauri/Cargo.toml"
dep() {
    local name="$1"
    local line
    line="$(grep -m1 "^$name = " "$APP_MANIFEST" || true)"
    [ -n "$line" ] || { echo "dipendenza non trovata nel manifest dell'app: $name" >&2; exit 1; }
    # Drop a trailing comment and any `optional = true`: here nothing is optional.
    line="${line%%#*}"
    echo "${line//, optional = true/}" | sed 's/optional = true, //; s/[[:space:]]*$//'
}

{
    cat <<'HEAD'
# Generated by scripts/aerorsync-emit.sh. Do not edit by hand: edit the script.
[package]
name = "aerorsync"
version = "0.1.0-alpha.1"
edition = "2021"
publish = false

[dependencies]
HEAD
    for d in async-trait russh secrecy serde sha2 ssh2 tokio xxhash-rust \
             libc zstd tracing md-5 md4 sha1 base64 hex filetime; do
        dep "$d"
    done
    # flate2 needs a zlib backend for `Compress::new_with_window_bits`, which
    # `real_wire.rs` calls to speak the rsync deflate stream. In the
    # application that backend is on by accident: `zip`, pulled for archive
    # support, enables `zlib-rs`, and cargo unifies the features. Nothing
    # declares the dependency, so the day `zip` changes the module stops
    # compiling for a reason nobody would connect to it. Declared here.
    echo 'flate2 = { version = "1.0", features = ["zlib-rs"] }'
    cat <<'LINTS'

# The lane 3 tests are gated on a cfg the harness sets with RUSTFLAGS. Declared
# here for the same reason the application declares it: without the
# declaration `-D warnings` turns every one of those gates into an error.
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(ci_lane3)'] }
# Everything the application adapter calls has no caller here, because the
# adapter stays in the application: alone, the module's own entry points read
# as dead. That list is not noise, it is the item-level inventory of what the
# crate will have to export when it is extracted, so it is kept as a warning
# rather than silenced, and rather than left as an error that would make this
# lane red for the one reason we already understand.
dead_code = "warn"

[target.'cfg(target_os = "linux")'.dependencies]
LINTS
    for d in acl-sys posix-acl; do
        dep "$d"
    done
    cat <<'DEV'

[dev-dependencies]
DEV
    # Test-only, and only visible once the tests are compiled here: the module's
    # own suite decodes a serialized error and mints an ed25519 key.
    for d in tempfile serde_json rand_010; do
        dep "$d"
    done
} > "$OUT/Cargo.toml"

# 3. The frozen real-rsync transcript the oracle tests read. 92 KB, five files.
#    Without it those tests do not fail, they return early and pass: that is the
#    silent skip the A0 tranche removed from this repository, and re-emitting the
#    module without the fixture would put it straight back.
FROZEN="$SRC/capture/artifacts_real/frozen"
if [ -d "$FROZEN" ]; then
    mkdir -p "$OUT/capture/artifacts_real/frozen"
    cp -a "$FROZEN"/. "$OUT/capture/artifacts_real/frozen/"
else
    echo "attenzione: fixture congelate assenti in $FROZEN, la suite emessa saltera' gli oracoli" >&2
fi

# 4. A manifest of what was emitted, so two runs can be compared without
#    diffing trees by eye.
( cd "$OUT" && find . -type f ! -name 'EMITTED.sha256' \
    | LC_ALL=C sort | xargs sha256sum ) > "$OUT/EMITTED.sha256"

echo "emesso in $OUT"
echo "file: $(grep -c . "$OUT/EMITTED.sha256")"
echo "manifest: $(sha256sum "$OUT/EMITTED.sha256" | cut -d' ' -f1)"
