// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 axpnet -- AI-assisted (see AI-TRANSPARENCY.md)
//
// AeroSync script export/import (issue #133). Produces and consumes a
// round-trippable `.aeroftp-script` file that captures a SyncProfile
// plus the path pair and the connection reference. Optional `.ps1` /
// `.sh` wrappers exist so an end user can double-click the script or
// hook it into Task Scheduler / cron; the wrapper just invokes
// `aeroftp-cli batch <name>.aeroftp-script` and stays content-free.

use crate::sync::{CompareDirection, RetryPolicy, SyncProfile, VerifyPolicy};
use crate::transfer_pool::CompressionMode;
use chrono::Utc;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

pub const HEADER_MARKER: &str = "# @aerosync:1";
pub const META_PREFIX: &str = "# @aerosync-meta:";
pub const CANONICAL_EXTENSION: &str = "aeroftp-script";

const KNOWN_META_FIELDS: &[&str] = &[
    "format",
    "format_version",
    "generated_by",
    "generated_at",
    "profile_id",
    "profile_name",
    "builtin",
    "retry_policy",
    "verify_policy",
    "parallel_streams",
    "compression_mode",
    "compare_timestamp",
    "compare_size",
    "compare_checksum",
];

const CONFLICT_MODES: &[&str] = &["newer", "older", "larger", "smaller", "rename", "skip"];

/// Wire format for AeroSync script export/import. Embeds the
/// authoritative `SyncProfile`, the path pair, and a connection
/// reference. CLI-level runtime knobs (`dry_run`, `conflict_mode`,
/// `watch`, ...) ride alongside because the CLI accepts them as flags
/// but they are not stored on the profile itself.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AerosyncScriptProfile {
    pub profile: SyncProfile,
    pub local_path: String,
    pub remote_path: String,
    /// Preferred connection reference: `--profile "<saved-server-name>"`.
    /// Export always emits this when present so credentials never leak.
    pub connect_profile: Option<String>,
    /// Fallback connection reference: literal URL. Only honoured on
    /// import for hand-edited scripts; export never writes a URL.
    pub connect_url: Option<String>,
    #[serde(default)]
    pub dry_run: bool,
    #[serde(default)]
    pub conflict_mode: Option<String>,
    #[serde(default)]
    pub track_renames: bool,
    #[serde(default)]
    pub skip_matching: bool,
    #[serde(default)]
    pub resync: bool,
    #[serde(default)]
    pub watch: bool,
}

/// Outcome of `parse_script`. `unmapped_fields` lists metadata keys
/// found in the header that were not understood (forward compatibility
/// signal). `warnings` describes recoverable parse anomalies.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParsedScript {
    pub profile: AerosyncScriptProfile,
    pub unmapped_fields: Vec<String>,
    pub warnings: Vec<String>,
}

#[derive(Debug, thiserror::Error, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ParseError {
    #[error("missing @aerosync:1 header marker")]
    MissingHeader,
    #[error("malformed metadata JSON at line {line}: {message}")]
    MalformedMetadata { line: usize, message: String },
    #[error("missing CONNECT directive")]
    MissingConnect,
    #[error("missing SYNC directive")]
    MissingSync,
    #[error("multiple SYNC directives, second one at line {line}")]
    MultipleSync { line: usize },
    #[error("malformed CONNECT directive at line {line}: {message}")]
    MalformedConnect { line: usize, message: String },
    #[error("malformed SYNC directive at line {line}: {message}")]
    MalformedSync { line: usize, message: String },
    #[error("undefined SET variable '{name}' at line {line}")]
    UndefinedVariable { line: usize, name: String },
}

impl ParseError {
    pub fn user_message(&self) -> String {
        self.to_string()
    }
}

/// Render a `SyncProfile` + path pair + connection ref as a canonical
/// `.aeroftp-script`. Variables `${LOCAL}` and `${REMOTE}` are exposed
/// so the script reads naturally and the path pair is editable in one
/// place at the top.
pub fn generate_script(profile: &AerosyncScriptProfile, app_version: &str) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER_MARKER);
    out.push('\n');
    out.push_str(&format!(
        "# Generated by AeroFTP {} on {}\n",
        app_version,
        Utc::now().to_rfc3339()
    ));
    out.push_str("# DO NOT edit the @aerosync metadata block by hand; use the GUI Import button\n");
    out.push_str("# to round-trip changes safely.\n");
    out.push_str("#\n");

    let meta = build_metadata_json(profile, app_version);
    let meta_text = serde_json::to_string_pretty(&meta).unwrap_or_else(|_| "{}".to_string());
    out.push_str(META_PREFIX);
    out.push('\n');
    for line in meta_text.lines() {
        out.push_str("# ");
        out.push_str(line);
        out.push('\n');
    }
    out.push('\n');

    // CLAUDE-AV-B3-05: quote the SET values. The parser captures the value
    // verbatim (rest of line) into the variable, then `SYNC ${LOCAL} ${REMOTE}`
    // expands and is re-tokenized on whitespace. Without quoting, a path with a
    // space (`/Users/John Smith/Docs`) word-splits into the wrong local/remote
    // pair on re-import; the quote-aware `tokenize` reconstructs the exact value
    // when the quotes ride inside the variable. Mirrors the excludes/CONNECT.
    out.push_str(&format!("SET LOCAL={}\n", shell_quote(&profile.local_path)));
    out.push_str(&format!(
        "SET REMOTE={}\n",
        shell_quote(&profile.remote_path)
    ));
    out.push('\n');

    if let Some(name) = profile.connect_profile.as_deref() {
        out.push_str(&format!("CONNECT --profile {}\n", shell_quote(name)));
    } else if let Some(url) = profile.connect_url.as_deref() {
        out.push_str(&format!("CONNECT {}\n", shell_quote(url)));
    } else {
        out.push_str("CONNECT --profile \"\"\n");
    }
    out.push('\n');

    out.push_str("SYNC ${LOCAL} ${REMOTE}");
    let direction_flag = direction_to_flag(profile.profile.direction);
    out.push_str(" \\\n  --direction ");
    out.push_str(direction_flag);
    if profile.profile.delete_orphans {
        out.push_str(" \\\n  --delete");
    }
    if profile.dry_run {
        out.push_str(" \\\n  --dry-run");
    }
    if profile.track_renames {
        out.push_str(" \\\n  --track-renames");
    }
    if profile.skip_matching {
        out.push_str(" \\\n  --skip-matching");
    }
    if profile.resync {
        out.push_str(" \\\n  --resync");
    }
    if profile.watch {
        out.push_str(" \\\n  --watch");
    }
    if let Some(mode) = profile.conflict_mode.as_deref() {
        if CONFLICT_MODES.contains(&mode) {
            out.push_str(" \\\n  --conflict-mode ");
            out.push_str(mode);
        }
    }
    for pattern in &profile.profile.exclude_patterns {
        out.push_str(" \\\n  --exclude ");
        out.push_str(&shell_quote(pattern));
    }
    out.push('\n');
    out.push('\n');

    out.push_str("DISCONNECT\n");
    out
}

/// Parse a `.aeroftp-script`. Hand-edited scripts are tolerated as long
/// as the canonical header marker is present and CONNECT + SYNC are
/// well-formed. Unknown metadata keys are reported via
/// `unmapped_fields` for forward compatibility.
pub fn parse_script(content: &str) -> Result<ParsedScript, ParseError> {
    let mut warnings: Vec<String> = Vec::new();
    let mut unmapped: Vec<String> = Vec::new();
    let mut header_seen = false;
    let mut meta_collecting = false;
    let mut meta_lines: Vec<String> = Vec::new();
    let mut meta_start_line: usize = 0;
    let mut variables: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    let mut connect_args: Option<String> = None;
    let mut connect_line: usize = 0;
    let mut sync_args: Option<String> = None;
    let mut sync_line: usize = 0;
    let mut disconnect_seen = false;

    let lines: Vec<&str> = content.lines().collect();
    let mut idx = 0;
    while idx < lines.len() {
        let raw = lines[idx];
        let line_num = idx + 1;
        let trimmed = raw.trim();

        // Header marker: the FIRST non-blank line must be the marker.
        if !header_seen {
            if trimmed.is_empty() {
                idx += 1;
                continue;
            }
            if trimmed == HEADER_MARKER {
                header_seen = true;
                idx += 1;
                continue;
            }
            return Err(ParseError::MissingHeader);
        }

        // Metadata block: starts at `# @aerosync-meta:`, then continues
        // as long as the next non-blank line is a `# ...` line. The
        // collected JSON is parsed in one shot afterwards.
        if trimmed == META_PREFIX {
            meta_collecting = true;
            meta_start_line = line_num;
            meta_lines.clear();
            idx += 1;
            while idx < lines.len() {
                let inner = lines[idx];
                let it = inner.trim_start();
                if let Some(rest) = it.strip_prefix("# ") {
                    meta_lines.push(rest.to_string());
                } else if it == "#" {
                    meta_lines.push(String::new());
                } else if it.starts_with('#') {
                    // a bare `#xxx` (no space): preserve verbatim minus `#`
                    meta_lines.push(it.trim_start_matches('#').to_string());
                } else {
                    break;
                }
                idx += 1;
            }
            continue;
        }

        // Blank / comment lines outside the meta block: skip silently.
        if trimmed.is_empty() || trimmed.starts_with('#') {
            idx += 1;
            continue;
        }

        // SET VAR=value
        if let Some(rest) = trimmed.strip_prefix("SET ") {
            if let Some(eq) = rest.find('=') {
                let name = rest[..eq].trim().to_string();
                let value = rest[eq + 1..].trim().to_string();
                if !name.is_empty() {
                    variables.insert(name, value);
                } else {
                    warnings.push(format!(
                        "line {}: SET with empty variable name ignored",
                        line_num
                    ));
                }
            } else {
                warnings.push(format!(
                    "line {}: SET without '=' ignored: '{}'",
                    line_num, rest
                ));
            }
            idx += 1;
            continue;
        }

        // CONNECT ...
        if let Some(rest) = trimmed.strip_prefix("CONNECT") {
            let body = rest.trim();
            connect_args = Some(body.to_string());
            connect_line = line_num;
            idx += 1;
            continue;
        }

        // SYNC ... (single logical line, '\' continuation allowed)
        if let Some(rest) = trimmed.strip_prefix("SYNC") {
            let body = collect_continued_line(rest, &lines, &mut idx);
            if sync_args.is_some() {
                return Err(ParseError::MultipleSync { line: line_num });
            }
            sync_args = Some(body);
            sync_line = line_num;
            continue;
        }

        // DISCONNECT (no-op for our purposes, just mark seen)
        if trimmed == "DISCONNECT" {
            disconnect_seen = true;
            idx += 1;
            continue;
        }

        // Any other directive: not part of AeroSync export but legal in
        // a batch script. Record as a warning.
        warnings.push(format!(
            "line {}: unrecognized directive '{}' ignored",
            line_num,
            trimmed.split_whitespace().next().unwrap_or("?")
        ));
        idx += 1;
    }

    if !header_seen {
        return Err(ParseError::MissingHeader);
    }
    let _ = disconnect_seen;

    // Metadata JSON parse, if a block was present.
    let metadata_json: serde_json::Value = if meta_collecting && !meta_lines.is_empty() {
        let joined = meta_lines.join("\n");
        match serde_json::from_str::<serde_json::Value>(&joined) {
            Ok(v) => v,
            Err(e) => {
                return Err(ParseError::MalformedMetadata {
                    line: meta_start_line,
                    message: e.to_string(),
                });
            }
        }
    } else {
        serde_json::Value::Object(serde_json::Map::new())
    };

    if let Some(obj) = metadata_json.as_object() {
        for key in obj.keys() {
            if !KNOWN_META_FIELDS.contains(&key.as_str()) {
                unmapped.push(key.clone());
            }
        }
    }

    // CONNECT must exist.
    let connect_args = connect_args.ok_or(ParseError::MissingConnect)?;
    let expanded_connect = expand_variables(&connect_args, &variables, connect_line)?;
    let (connect_profile, connect_url) = parse_connect(&expanded_connect, connect_line)?;

    // SYNC must exist.
    let sync_args = sync_args.ok_or(ParseError::MissingSync)?;
    let expanded_sync = expand_variables(&sync_args, &variables, sync_line)?;
    let parsed_sync = parse_sync(&expanded_sync, sync_line)?;

    // Build the SyncProfile from metadata + sync line. Metadata is
    // authoritative for header-only fields; SYNC flags are
    // authoritative for the fields they cover. Where both are present
    // and disagree, the flag wins (matches handoff spec).
    let mut profile = SyncProfile {
        id: metadata_json
            .get("profile_id")
            .and_then(|v| v.as_str())
            .unwrap_or("imported")
            .to_string(),
        name: metadata_json
            .get("profile_name")
            .and_then(|v| v.as_str())
            .unwrap_or("Imported preset")
            .to_string(),
        builtin: metadata_json
            .get("builtin")
            .and_then(|v| v.as_bool())
            .unwrap_or(false),
        direction: parsed_sync.direction,
        compare_timestamp: metadata_json
            .get("compare_timestamp")
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        compare_size: metadata_json
            .get("compare_size")
            .and_then(|v| v.as_bool())
            .unwrap_or(true),
        compare_checksum: metadata_json
            .get("compare_checksum")
            .and_then(|v| v.as_bool())
            .unwrap_or(false),
        exclude_patterns: parsed_sync.exclude_patterns,
        retry_policy: metadata_json
            .get("retry_policy")
            .and_then(|v| serde_json::from_value::<RetryPolicy>(v.clone()).ok())
            .unwrap_or_default(),
        verify_policy: metadata_json
            .get("verify_policy")
            .and_then(|v| serde_json::from_value::<VerifyPolicy>(v.clone()).ok())
            .unwrap_or_default(),
        delete_orphans: parsed_sync.delete_orphans,
        parallel_streams: metadata_json
            .get("parallel_streams")
            .and_then(|v| v.as_u64())
            .map(|n| n.clamp(1, 8) as u8)
            .unwrap_or(1),
        compression_mode: metadata_json
            .get("compression_mode")
            .and_then(|v| serde_json::from_value::<CompressionMode>(v.clone()).ok())
            .unwrap_or_default(),
    };

    // Mirror builtin flag from explicit metadata if the consumer wants
    // it; new IDs default to builtin=false.
    let _ = &mut profile;

    let (local_path, remote_path) = parsed_sync.path_pair;

    let result = AerosyncScriptProfile {
        profile,
        local_path,
        remote_path,
        connect_profile,
        connect_url,
        dry_run: parsed_sync.dry_run,
        conflict_mode: parsed_sync.conflict_mode,
        track_renames: parsed_sync.track_renames,
        skip_matching: parsed_sync.skip_matching,
        resync: parsed_sync.resync,
        watch: parsed_sync.watch,
    };

    Ok(ParsedScript {
        profile: result,
        unmapped_fields: unmapped,
        warnings,
    })
}

/// PowerShell wrapper that just invokes `aeroftp-cli batch <name>`
/// against the sibling canonical script. Updates regenerate the
/// canonical file only; the wrapper resolves the sibling via
/// `Split-Path` at runtime.
pub fn ps1_wrapper(canonical_filename: &str) -> String {
    format!(
        r#"#!/usr/bin/env pwsh
# Auto-generated by AeroFTP. Do not edit; regenerate from the GUI.
# This wrapper exists so the script can be double-clicked or scheduled
# by the OS task system. The actual logic lives in the .aeroftp-script
# file next to it.

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
& aeroftp-cli batch (Join-Path $here {}) @args
exit $LASTEXITCODE
"#,
        ps1_quote(canonical_filename)
    )
}

/// POSIX shell wrapper. Same shape as the `.ps1`, resolved via
/// `dirname` so the sibling script is found regardless of CWD.
pub fn sh_wrapper(canonical_filename: &str) -> String {
    format!(
        r#"#!/bin/sh
# Auto-generated by AeroFTP. Do not edit; regenerate from the GUI.
# This wrapper exists so the script can be double-clicked or scheduled
# by the OS task system. The actual logic lives in the .aeroftp-script
# file next to it.

set -e
here="$(cd "$(dirname "$0")" && pwd)"
exec aeroftp-cli batch "$here/{}" "$@"
"#,
        sh_quote_body(canonical_filename)
    )
}

/// If the input file looks like a wrapper (`.ps1` / `.sh`), parse the
/// `aeroftp-cli batch <something>.aeroftp-script` reference inside and
/// return the resolved sibling path. Returns `None` when the file is
/// the canonical script itself or no wrapper reference is found.
pub fn detect_wrapper_target(path: &Path, content: &str) -> Option<PathBuf> {
    let ext = path
        .extension()
        .and_then(|s| s.to_str())
        .map(|s| s.to_ascii_lowercase())
        .unwrap_or_default();
    if ext != "ps1" && ext != "sh" {
        return None;
    }
    // Look for the canonical reference in any quoting style.
    let needle = ".aeroftp-script";
    for line in content.lines() {
        let lower = line.to_ascii_lowercase();
        if !lower.contains("aeroftp-cli") || !lower.contains("batch") {
            continue;
        }
        if let Some(pos) = lower.find(needle) {
            // Walk left until the start of the filename token.
            let mut start = pos;
            let bytes = line.as_bytes();
            while start > 0 {
                let b = bytes[start - 1];
                if b == b'"' || b == b'\'' || b == b' ' || b == b'\t' || b == b'(' {
                    break;
                }
                start -= 1;
            }
            let end = pos + needle.len();
            if end <= line.len() {
                let filename: String = line[start..end].to_string();
                // Strip wrapper-specific path joining: keep just the
                // filename component, then resolve against the
                // wrapper's parent.
                let bare = Path::new(&filename)
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or(filename.as_str())
                    .to_string();
                let parent = path.parent().unwrap_or_else(|| Path::new("."));
                return Some(parent.join(bare));
            }
        }
    }
    None
}

// ---------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------

fn build_metadata_json(profile: &AerosyncScriptProfile, app_version: &str) -> serde_json::Value {
    let mut map = serde_json::Map::new();
    map.insert(
        "format".to_string(),
        serde_json::Value::String("aerosync-script".to_string()),
    );
    map.insert(
        "format_version".to_string(),
        serde_json::Value::Number(serde_json::Number::from(1)),
    );
    map.insert(
        "generated_by".to_string(),
        serde_json::Value::String(format!("AeroFTP {}", app_version)),
    );
    map.insert(
        "generated_at".to_string(),
        serde_json::Value::String(Utc::now().to_rfc3339()),
    );
    map.insert(
        "profile_id".to_string(),
        serde_json::Value::String(profile.profile.id.clone()),
    );
    map.insert(
        "profile_name".to_string(),
        serde_json::Value::String(profile.profile.name.clone()),
    );
    map.insert(
        "builtin".to_string(),
        serde_json::Value::Bool(profile.profile.builtin),
    );
    if let Ok(v) = serde_json::to_value(&profile.profile.retry_policy) {
        map.insert("retry_policy".to_string(), v);
    }
    if let Ok(v) = serde_json::to_value(&profile.profile.verify_policy) {
        map.insert("verify_policy".to_string(), v);
    }
    map.insert(
        "parallel_streams".to_string(),
        serde_json::Value::Number(serde_json::Number::from(profile.profile.parallel_streams)),
    );
    if let Ok(v) = serde_json::to_value(&profile.profile.compression_mode) {
        map.insert("compression_mode".to_string(), v);
    }
    map.insert(
        "compare_timestamp".to_string(),
        serde_json::Value::Bool(profile.profile.compare_timestamp),
    );
    map.insert(
        "compare_size".to_string(),
        serde_json::Value::Bool(profile.profile.compare_size),
    );
    map.insert(
        "compare_checksum".to_string(),
        serde_json::Value::Bool(profile.profile.compare_checksum),
    );
    serde_json::Value::Object(map)
}

fn direction_to_flag(direction: CompareDirection) -> &'static str {
    match direction {
        CompareDirection::LocalToRemote => "upload",
        CompareDirection::RemoteToLocal => "download",
        CompareDirection::Bidirectional => "both",
    }
}

fn flag_to_direction(flag: &str) -> Option<CompareDirection> {
    match flag {
        "upload" => Some(CompareDirection::LocalToRemote),
        "download" => Some(CompareDirection::RemoteToLocal),
        "both" | "bidirectional" => Some(CompareDirection::Bidirectional),
        _ => None,
    }
}

/// Double-quote a shell token, escaping `\` and `"`.
fn shell_quote(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

/// PowerShell single-quote a literal.
fn ps1_quote(value: &str) -> String {
    let escaped = value.replace('\'', "''");
    format!("'{}'", escaped)
}

/// Body-safe sh-quote: escape `"`, `$`, backslash so the wrapper
/// template's surrounding double quotes still bind correctly.
fn sh_quote_body(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '$' => out.push_str("\\$"),
            '\\' => out.push_str("\\\\"),
            '`' => out.push_str("\\`"),
            _ => out.push(ch),
        }
    }
    out
}

fn expand_variables(
    body: &str,
    vars: &std::collections::HashMap<String, String>,
    line: usize,
) -> Result<String, ParseError> {
    // CLAUDE-AV-B3-04: scan by `str` slices, never by raw bytes. The prior
    // fallback computed a char length from `(b as char).len_utf8()` on a RAW
    // byte, which for a multi-byte UTF-8 lead byte (e.g. 0xE7) yields the wrong
    // length and slices mid-character, panicking on any non-ASCII literal path
    // in a SYNC/CONNECT line. `find("${")` and slicing at the returned char
    // boundaries is UTF-8-safe.
    let mut out = String::with_capacity(body.len());
    let mut rest = body;
    while let Some(pos) = rest.find("${") {
        out.push_str(&rest[..pos]);
        let after = &rest[pos + 2..];
        if let Some(end) = after.find('}') {
            let name = &after[..end];
            match vars.get(name) {
                Some(v) => out.push_str(v),
                None => {
                    return Err(ParseError::UndefinedVariable {
                        line,
                        name: name.to_string(),
                    });
                }
            }
            rest = &after[end + 1..];
        } else {
            // No closing brace: emit the literal "${" and keep scanning after it
            // (preserves the pre-fix behavior for an unterminated variable).
            out.push_str("${");
            rest = after;
        }
    }
    out.push_str(rest);
    Ok(out)
}

/// Collect a logical line that may span multiple physical lines via
/// trailing `\` continuations. Advances `idx` past the joined region.
fn collect_continued_line(first: &str, lines: &[&str], idx: &mut usize) -> String {
    let mut joined = first.trim().to_string();
    *idx += 1;
    loop {
        if joined.ends_with('\\') {
            joined.pop(); // strip the trailing backslash
            joined.push(' ');
            if *idx >= lines.len() {
                break;
            }
            let next = lines[*idx].trim();
            joined.push_str(next);
            *idx += 1;
            continue;
        }
        break;
    }
    joined
}

fn parse_connect(body: &str, line: usize) -> Result<(Option<String>, Option<String>), ParseError> {
    let tokens =
        tokenize(body, line).map_err(|message| ParseError::MalformedConnect { line, message })?;
    let mut it = tokens.into_iter().peekable();
    let mut profile: Option<String> = None;
    let mut url: Option<String> = None;
    while let Some(tok) = it.next() {
        match tok.as_str() {
            "--profile" => {
                let v = it.next().ok_or_else(|| ParseError::MalformedConnect {
                    line,
                    message: "--profile expects a value".to_string(),
                })?;
                profile = Some(v);
            }
            other if !other.starts_with('-') && profile.is_none() && url.is_none() => {
                // Treat the first positional token as a URL when no
                // --profile is given.
                url = Some(other.to_string());
            }
            _ => {}
        }
    }
    if profile.is_none() && url.is_none() {
        return Err(ParseError::MalformedConnect {
            line,
            message: "expected --profile <name> or a URL".to_string(),
        });
    }
    Ok((profile, url))
}

struct ParsedSyncLine {
    path_pair: (String, String),
    direction: CompareDirection,
    delete_orphans: bool,
    dry_run: bool,
    track_renames: bool,
    skip_matching: bool,
    resync: bool,
    watch: bool,
    conflict_mode: Option<String>,
    exclude_patterns: Vec<String>,
}

fn parse_sync(body: &str, line: usize) -> Result<ParsedSyncLine, ParseError> {
    let tokens =
        tokenize(body, line).map_err(|message| ParseError::MalformedSync { line, message })?;
    let mut positional: Vec<String> = Vec::new();
    let mut direction: Option<CompareDirection> = None;
    let mut delete_orphans = false;
    let mut dry_run = false;
    let mut track_renames = false;
    let mut skip_matching = false;
    let mut resync = false;
    let mut watch = false;
    let mut conflict_mode: Option<String> = None;
    let mut exclude_patterns: Vec<String> = Vec::new();
    let mut it = tokens.into_iter().peekable();
    while let Some(tok) = it.next() {
        match tok.as_str() {
            "--direction" => {
                let v = it.next().ok_or_else(|| ParseError::MalformedSync {
                    line,
                    message: "--direction expects a value".to_string(),
                })?;
                direction =
                    Some(
                        flag_to_direction(&v).ok_or_else(|| ParseError::MalformedSync {
                            line,
                            message: format!("unknown direction '{}'", v),
                        })?,
                    );
            }
            "--delete" => delete_orphans = true,
            "--dry-run" => dry_run = true,
            "--track-renames" => track_renames = true,
            "--skip-matching" => skip_matching = true,
            "--resync" => resync = true,
            "--watch" => watch = true,
            "--conflict-mode" => {
                let v = it.next().ok_or_else(|| ParseError::MalformedSync {
                    line,
                    message: "--conflict-mode expects a value".to_string(),
                })?;
                if !CONFLICT_MODES.contains(&v.as_str()) {
                    return Err(ParseError::MalformedSync {
                        line,
                        message: format!("unknown conflict mode '{}'", v),
                    });
                }
                conflict_mode = Some(v);
            }
            "--exclude" | "-e" => {
                let v = it.next().ok_or_else(|| ParseError::MalformedSync {
                    line,
                    message: "--exclude expects a pattern".to_string(),
                })?;
                exclude_patterns.push(v);
            }
            other if other.starts_with("--") => {
                // Forward-compat: ignore unknown long flags but try to
                // also consume their value if it does not look like a
                // flag itself.
                if let Some(next) = it.peek() {
                    if !next.starts_with('-') {
                        let _ = it.next();
                    }
                }
            }
            _ => positional.push(tok),
        }
    }
    if positional.len() < 2 {
        return Err(ParseError::MalformedSync {
            line,
            message: format!(
                "expected local + remote path arguments, got {}",
                positional.len()
            ),
        });
    }
    let direction = direction.ok_or_else(|| ParseError::MalformedSync {
        line,
        message: "missing --direction".to_string(),
    })?;
    let local = positional[0].clone();
    let remote = positional[1].clone();
    Ok(ParsedSyncLine {
        path_pair: (local, remote),
        direction,
        delete_orphans,
        dry_run,
        track_renames,
        skip_matching,
        resync,
        watch,
        conflict_mode,
        exclude_patterns,
    })
}

/// Tokenise a shell-style command body. Supports double and single
/// quotes and `\` escapes inside double-quoted regions.
fn tokenize(body: &str, _line: usize) -> Result<Vec<String>, String> {
    let mut out: Vec<String> = Vec::new();
    let mut current = String::new();
    let mut in_double = false;
    let mut in_single = false;
    let mut escape = false;
    let mut has_token = false;
    for ch in body.chars() {
        if escape {
            current.push(ch);
            escape = false;
            has_token = true;
            continue;
        }
        match ch {
            '\\' if in_double => {
                escape = true;
            }
            '"' if !in_single => {
                in_double = !in_double;
                has_token = true;
            }
            '\'' if !in_double => {
                in_single = !in_single;
                has_token = true;
            }
            c if c.is_whitespace() && !in_double && !in_single => {
                if has_token {
                    out.push(std::mem::take(&mut current));
                    has_token = false;
                }
            }
            c => {
                current.push(c);
                has_token = true;
            }
        }
    }
    if in_double || in_single {
        return Err("unterminated quoted token".to_string());
    }
    if has_token {
        out.push(current);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample(profile: SyncProfile) -> AerosyncScriptProfile {
        AerosyncScriptProfile {
            profile,
            local_path: "/home/user/photos".to_string(),
            remote_path: "/backups/photos".to_string(),
            connect_profile: Some("Home NAS".to_string()),
            connect_url: None,
            dry_run: false,
            conflict_mode: Some("newer".to_string()),
            track_renames: false,
            skip_matching: false,
            resync: false,
            watch: false,
        }
    }

    #[test]
    fn round_trip_mirror_preset() {
        let original = sample(SyncProfile::mirror());
        let text = generate_script(&original, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert_eq!(parsed.profile.profile.id, original.profile.id);
        assert_eq!(parsed.profile.profile.name, original.profile.name);
        assert_eq!(parsed.profile.profile.direction, original.profile.direction);
        assert_eq!(
            parsed.profile.profile.exclude_patterns,
            original.profile.exclude_patterns
        );
        assert_eq!(
            parsed.profile.profile.delete_orphans,
            original.profile.delete_orphans
        );
        assert_eq!(
            parsed.profile.profile.parallel_streams,
            original.profile.parallel_streams
        );
        assert_eq!(parsed.profile.local_path, original.local_path);
        assert_eq!(parsed.profile.remote_path, original.remote_path);
        assert_eq!(parsed.profile.connect_profile, original.connect_profile);
        assert_eq!(parsed.profile.conflict_mode, original.conflict_mode);
        assert!(parsed.unmapped_fields.is_empty());
    }

    #[test]
    fn round_trip_two_way_preset() {
        let original = sample(SyncProfile::two_way());
        let text = generate_script(&original, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert_eq!(
            parsed.profile.profile.direction,
            CompareDirection::Bidirectional
        );
        assert!(!parsed.profile.profile.delete_orphans);
    }

    /// CLAUDE-AV-B3-05: a local/remote path with spaces must survive the
    /// generate/parse round-trip. Pre-fix the unquoted SET value word-split on
    /// re-import into the wrong local/remote pair.
    #[test]
    fn round_trip_paths_with_spaces_preserve_pair() {
        let mut original = sample(SyncProfile::mirror());
        original.local_path = "/Users/John Smith/My Documents".to_string();
        original.remote_path = "/srv/back ups/John".to_string();
        let text = generate_script(&original, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert_eq!(parsed.profile.local_path, original.local_path);
        assert_eq!(parsed.profile.remote_path, original.remote_path);
    }

    /// CLAUDE-AV-B3-04: `expand_variables` must be UTF-8-safe. Pre-fix, a
    /// non-ASCII literal (not routed through a `${VAR}`) in a SYNC/CONNECT line
    /// panicked on a non-char-boundary byte slice.
    #[test]
    fn expand_variables_non_ascii_literal_does_not_panic() {
        let mut vars = std::collections::HashMap::new();
        vars.insert("LOCAL".to_string(), "/data".to_string());
        let out = expand_variables("${LOCAL}/照片 /backup 4-byte:\u{1F600}", &vars, 1).unwrap();
        assert_eq!(out, "/data/照片 /backup 4-byte:\u{1F600}");
        // Unterminated variable is preserved literally, not panicked on.
        let raw = expand_variables("a ${OPEN and 文字", &vars, 1).unwrap();
        assert_eq!(raw, "a ${OPEN and 文字");
    }

    #[test]
    fn round_trip_backup_preset() {
        let original = sample(SyncProfile::backup());
        let text = generate_script(&original, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert_eq!(parsed.profile.profile.verify_policy, VerifyPolicy::Full);
        assert_eq!(parsed.profile.profile.retry_policy.max_retries, 5);
        assert!(parsed.profile.profile.compare_checksum);
        assert!(!parsed.profile.profile.compare_timestamp);
    }

    #[test]
    fn round_trip_pull_preset() {
        let original = sample(SyncProfile::pull());
        let text = generate_script(&original, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert_eq!(
            parsed.profile.profile.direction,
            CompareDirection::RemoteToLocal
        );
        assert!(parsed.profile.profile.delete_orphans);
    }

    #[test]
    fn round_trip_remote_backup_preset() {
        let original = sample(SyncProfile::remote_backup());
        let text = generate_script(&original, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert_eq!(
            parsed.profile.profile.direction,
            CompareDirection::RemoteToLocal
        );
        assert!(!parsed.profile.profile.delete_orphans);
        assert!(parsed.profile.profile.compare_checksum);
    }

    #[test]
    fn round_trip_custom_extra_runtime_knobs() {
        let mut sp = SyncProfile::mirror();
        sp.id = "custom-1".into();
        sp.name = "Custom mirror".into();
        sp.builtin = false;
        sp.parallel_streams = 6;
        let mut original = sample(sp);
        original.dry_run = true;
        original.track_renames = true;
        original.watch = true;
        original.conflict_mode = Some("rename".into());

        let text = generate_script(&original, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert!(parsed.profile.dry_run);
        assert!(parsed.profile.track_renames);
        assert!(parsed.profile.watch);
        assert_eq!(parsed.profile.conflict_mode.as_deref(), Some("rename"));
        assert_eq!(parsed.profile.profile.parallel_streams, 6);
        assert_eq!(parsed.profile.profile.id, "custom-1");
    }

    #[test]
    fn missing_header_rejected() {
        let text = "SET LOCAL=/a\nCONNECT --profile \"x\"\nSYNC ${LOCAL} /b --direction both\n";
        let err = parse_script(text).expect_err("must reject");
        assert!(matches!(err, ParseError::MissingHeader));
    }

    #[test]
    fn malformed_metadata_rejected() {
        let text = format!(
            "{}\n{}\n# {{ not valid json\n# }}\n\nCONNECT --profile \"x\"\nSYNC /a /b --direction both\n",
            HEADER_MARKER, META_PREFIX
        );
        let err = parse_script(&text).expect_err("must reject");
        assert!(matches!(err, ParseError::MalformedMetadata { .. }));
    }

    #[test]
    fn missing_connect_rejected() {
        let text = format!("{}\nSYNC /a /b --direction both\n", HEADER_MARKER);
        let err = parse_script(&text).expect_err("must reject");
        assert!(matches!(err, ParseError::MissingConnect));
    }

    #[test]
    fn missing_sync_rejected() {
        let text = format!("{}\nCONNECT --profile \"x\"\nDISCONNECT\n", HEADER_MARKER);
        let err = parse_script(&text).expect_err("must reject");
        assert!(matches!(err, ParseError::MissingSync));
    }

    #[test]
    fn multiple_sync_rejected() {
        let text = format!(
            "{}\nCONNECT --profile \"x\"\nSYNC /a /b --direction both\nSYNC /c /d --direction both\n",
            HEADER_MARKER
        );
        let err = parse_script(&text).expect_err("must reject");
        assert!(matches!(err, ParseError::MultipleSync { line: 4 }));
    }

    #[test]
    fn undefined_variable_rejected() {
        let text = format!(
            "{}\nCONNECT --profile \"x\"\nSYNC ${{MISSING}} /b --direction both\n",
            HEADER_MARKER
        );
        let err = parse_script(&text).expect_err("must reject");
        assert!(matches!(err, ParseError::UndefinedVariable { .. }));
    }

    #[test]
    fn unknown_metadata_keys_reported_as_unmapped() {
        let text = format!(
            "{}\n{}\n# {{\n#   \"format\": \"aerosync-script\",\n#   \"format_version\": 1,\n#   \"future_field\": 42\n# }}\n\nCONNECT --profile \"x\"\nSYNC /a /b --direction both\n",
            HEADER_MARKER, META_PREFIX
        );
        let parsed = parse_script(&text).expect("must parse");
        assert!(parsed.unmapped_fields.contains(&"future_field".to_string()));
    }

    #[test]
    fn ps1_wrapper_references_canonical_sibling() {
        let w = ps1_wrapper("mirror-to-nas.aeroftp-script");
        assert!(w.contains("aeroftp-cli batch"));
        assert!(w.contains("mirror-to-nas.aeroftp-script"));
        assert!(w.contains("#!/usr/bin/env pwsh"));
    }

    #[test]
    fn sh_wrapper_references_canonical_sibling() {
        let w = sh_wrapper("mirror-to-nas.aeroftp-script");
        assert!(w.contains("aeroftp-cli batch"));
        assert!(w.contains("mirror-to-nas.aeroftp-script"));
        assert!(w.starts_with("#!/bin/sh"));
    }

    #[test]
    fn detect_wrapper_target_ps1() {
        let wrapper_path = PathBuf::from("/tmp/foo/run.ps1");
        let content = ps1_wrapper("config.aeroftp-script");
        let target = detect_wrapper_target(&wrapper_path, &content);
        assert_eq!(
            target,
            Some(PathBuf::from("/tmp/foo/config.aeroftp-script"))
        );
    }

    #[test]
    fn detect_wrapper_target_sh() {
        let wrapper_path = PathBuf::from("/tmp/foo/run.sh");
        let content = sh_wrapper("config.aeroftp-script");
        let target = detect_wrapper_target(&wrapper_path, &content);
        assert_eq!(
            target,
            Some(PathBuf::from("/tmp/foo/config.aeroftp-script"))
        );
    }

    #[test]
    fn detect_wrapper_target_returns_none_for_canonical() {
        let wrapper_path = PathBuf::from("/tmp/foo/run.aeroftp-script");
        let content = "# @aerosync:1\nCONNECT --profile \"x\"\nSYNC /a /b --direction both\n";
        let target = detect_wrapper_target(&wrapper_path, content);
        assert!(target.is_none());
    }

    #[test]
    fn shell_quote_escapes_backslash_and_quote() {
        assert_eq!(shell_quote("plain"), "\"plain\"");
        assert_eq!(shell_quote("a\"b"), "\"a\\\"b\"");
        assert_eq!(shell_quote("a\\b"), "\"a\\\\b\"");
    }

    #[test]
    fn metadata_flag_wins_over_header_when_disagreeing() {
        // Header says delete_orphans is implicit; SYNC line carries
        // --delete. The actual delete_orphans state comes from the
        // flag (the handoff's explicit contract).
        let mut profile = sample(SyncProfile::two_way());
        profile.profile.delete_orphans = true; // emit --delete
        let text = generate_script(&profile, "3.8.5-test");
        let parsed = parse_script(&text).expect("must parse");
        assert!(parsed.profile.profile.delete_orphans);
    }
}
